// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: score2.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type List2MatchesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Country string `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
}

func (x *List2MatchesRequest) Reset() {
	*x = List2MatchesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_score2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *List2MatchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*List2MatchesRequest) ProtoMessage() {}

func (x *List2MatchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_score2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use List2MatchesRequest.ProtoReflect.Descriptor instead.
func (*List2MatchesRequest) Descriptor() ([]byte, []int) {
	return file_score2_proto_rawDescGZIP(), []int{0}
}

func (x *List2MatchesRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type Match2ScoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score string `protobuf:"bytes,1,opt,name=score,proto3" json:"score,omitempty"`
	Live  bool   `protobuf:"varint,2,opt,name=live,proto3" json:"live,omitempty"`
}

func (x *Match2ScoreResponse) Reset() {
	*x = Match2ScoreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_score2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Match2ScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match2ScoreResponse) ProtoMessage() {}

func (x *Match2ScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_score2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match2ScoreResponse.ProtoReflect.Descriptor instead.
func (*Match2ScoreResponse) Descriptor() ([]byte, []int) {
	return file_score2_proto_rawDescGZIP(), []int{1}
}

func (x *Match2ScoreResponse) GetScore() string {
	if x != nil {
		return x.Score
	}
	return ""
}

func (x *Match2ScoreResponse) GetLive() bool {
	if x != nil {
		return x.Live
	}
	return false
}

type List2MatchesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scores []*Match2ScoreResponse `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
}

func (x *List2MatchesResponse) Reset() {
	*x = List2MatchesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_score2_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *List2MatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*List2MatchesResponse) ProtoMessage() {}

func (x *List2MatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_score2_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use List2MatchesResponse.ProtoReflect.Descriptor instead.
func (*List2MatchesResponse) Descriptor() ([]byte, []int) {
	return file_score2_proto_rawDescGZIP(), []int{2}
}

func (x *List2MatchesResponse) GetScores() []*Match2ScoreResponse {
	if x != nil {
		return x.Scores
	}
	return nil
}

var File_score2_proto protoreflect.FileDescriptor

var file_score2_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x32, 0x22, 0x2f, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x32, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x3f, 0x0a, 0x13, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x32, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x04, 0x6c, 0x69, 0x76, 0x65, 0x22, 0x4b, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74,
	0x32, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x33, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x32, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x32,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x73, 0x32, 0x5a, 0x0a, 0x0d, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x32, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x32, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x12, 0x1b, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x32, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x32, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x32, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x32, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_score2_proto_rawDescOnce sync.Once
	file_score2_proto_rawDescData = file_score2_proto_rawDesc
)

func file_score2_proto_rawDescGZIP() []byte {
	file_score2_proto_rawDescOnce.Do(func() {
		file_score2_proto_rawDescData = protoimpl.X.CompressGZIP(file_score2_proto_rawDescData)
	})
	return file_score2_proto_rawDescData
}

var file_score2_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_score2_proto_goTypes = []interface{}{
	(*List2MatchesRequest)(nil),  // 0: score2.List2MatchesRequest
	(*Match2ScoreResponse)(nil),  // 1: score2.Match2ScoreResponse
	(*List2MatchesResponse)(nil), // 2: score2.List2MatchesResponse
}
var file_score2_proto_depIdxs = []int32{
	1, // 0: score2.List2MatchesResponse.scores:type_name -> score2.Match2ScoreResponse
	0, // 1: score2.Score2Service.List2Matches:input_type -> score2.List2MatchesRequest
	2, // 2: score2.Score2Service.List2Matches:output_type -> score2.List2MatchesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_score2_proto_init() }
func file_score2_proto_init() {
	if File_score2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_score2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*List2MatchesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_score2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Match2ScoreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_score2_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*List2MatchesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_score2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_score2_proto_goTypes,
		DependencyIndexes: file_score2_proto_depIdxs,
		MessageInfos:      file_score2_proto_msgTypes,
	}.Build()
	File_score2_proto = out.File
	file_score2_proto_rawDesc = nil
	file_score2_proto_goTypes = nil
	file_score2_proto_depIdxs = nil
}
